name: "main"
on: push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (GitHub)
        uses: actions/checkout@v4

      - name: Deploy
        uses: ./
        with:
          private-key: ${{ secrets.PRIVATEKEY }}
          wallet-address: ${{ secrets.WALLET_ADDRESS }}
          dll-filename: HelloWorld.dll.patched

  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
